import io
import re
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Custom canvas that adds dynamic 'Page X of Y' footers and running headers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(36, 11 * inch - 26, "AI Travel Planner — Personalized Itinerary")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(36, 11 * inch - 30, 8.5 * inch - 36, 11 * inch - 30)

        # Running Footer (all pages)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 36, 22, page_str)
        self.drawString(36, 22, "Generated autonomously by AI Multi-Agent Travel Planner • PostgreSQL Checkpointed")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(36, 32, 8.5 * inch - 36, 32)

        self.restoreState()


def clean_xml_text(text: str) -> str:
    """Escapes special characters for ReportLab XML parser while preserving valid tags."""
    if not text:
        return ""
    # Protect existing XML ampersands
    text = text.replace("&", "&amp;")

    # 1. Bold + Italic: ***text*** or ___text___
    text = re.sub(r"\*\*\*(.+?)\*\*\*", r"<b><i>\1</i></b>", text)
    text = re.sub(r"___(.+?)___", r"<b><i>\1</i></b>", text)

    # 2. Bold: **text** or __text__
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"__(.+?)__", r"<b>\1</b>", text)

    # 3. Italic: *text* or _text_
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    text = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"<i>\1</i>", text)

    # 4. Inline code
    text = re.sub(r"`([^`]+)`", r'<font face="Courier" color="#0369A1">\1</font>', text)

    # 5. Markdown links [text](url) -> text (url)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<b>\1</b> (<font color="#0284C7">\2</font>)', text)

    # 6. Auto-repair misordered/overlapping tag pairs
    text = re.sub(r"<b><i>(.*?)</b></i>", r"<b><i>\1</i></b>", text)
    text = re.sub(r"<i><b>(.*?)</i></b>", r"<i><b>\1</b></i>", text)

    return text


def safe_paragraph(text: str, style, bulletText=None) -> Paragraph:
    """
    Safely instantiates a ReportLab Paragraph. If XML parsing fails due to malformed
    or unmatched tags generated by LLMs, it automatically strips the invalid tags
    and returns a clean paragraph without failing the document compilation.
    """
    if not text:
        return Paragraph("", style, bulletText=bulletText)
    try:
        return Paragraph(text, style, bulletText=bulletText)
    except Exception:
        # Fallback: Strip XML tags, re-escape special characters, and render plain text
        clean = re.sub(r"<[^>]+>", "", text)
        clean = clean.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        try:
            return Paragraph(clean, style, bulletText=bulletText)
        except Exception:
            return Paragraph("—", style, bulletText=bulletText)


def markdown_to_flowables(md_text: str, styles: dict) -> list:
    """Converts a Markdown string into a sequence of ReportLab flowable elements."""
    if not md_text:
        return []

    flowables = []
    lines = md_text.strip().split("\n")
    i = 0
    in_table = False
    table_rows = []

    while i < len(lines):
        line = lines[i].strip()

        # Handle Markdown Tables
        if "|" in line and line.startswith("|") and line.endswith("|"):
            cells = [c.strip() for c in line.split("|")[1:-1]]
            # Skip separator line like |---|---|
            if all(re.match(r"^:?-+:?$", c) for c in cells if c):
                i += 1
                continue
            table_rows.append(cells)
            i += 1
            # Check if next line is not a table row
            if i >= len(lines) or not ("|" in lines[i] and lines[i].strip().startswith("|")):
                if table_rows:
                    col_count = max(len(r) for r in table_rows)
                    # Normalize rows
                    norm_rows = []
                    for r_idx, r in enumerate(table_rows):
                        row_cells = []
                        for c_idx in range(col_count):
                            val = r[c_idx] if c_idx < len(r) else ""
                            style = styles["TableHeader"] if r_idx == 0 else styles["TableCell"]
                            row_cells.append(safe_paragraph(clean_xml_text(val), style))
                        norm_rows.append(row_cells)

                    t = Table(norm_rows, repeatRows=1)
                    t.setStyle(TableStyle([
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0284C7")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                        ("TOPPADDING", (0, 0), (-1, -1), 4),
                        ("LEFTPADDING", (0, 0), (-1, -1), 6),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F8FAFC"), colors.HexColor("#FFFFFF")]),
                        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ]))
                    flowables.append(Spacer(1, 4))
                    flowables.append(t)
                    flowables.append(Spacer(1, 6))
                    table_rows = []
            continue

        if not line:
            flowables.append(Spacer(1, 4))
            i += 1
            continue

        # Headers
        if line.startswith("# "):
            flowables.append(safe_paragraph(clean_xml_text(line[2:]), styles["DocH1"]))
            flowables.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0284C7"), spaceAfter=6))
        elif line.startswith("## "):
            flowables.append(safe_paragraph(clean_xml_text(line[3:]), styles["DocH2"]))
        elif line.startswith("### "):
            flowables.append(safe_paragraph(clean_xml_text(line[4:]), styles["DocH3"]))
        elif line.startswith("#### "):
            flowables.append(safe_paragraph(clean_xml_text(line[5:]), styles["DocH4"]))
        # Bullet list items
        elif line.startswith("- ") or line.startswith("* "):
            content = clean_xml_text(line[2:])
            flowables.append(safe_paragraph(f"• {content}", styles["DocBullet"]))
        elif re.match(r"^\d+\.\s", line):
            content = clean_xml_text(re.sub(r"^\d+\.\s", "", line))
            num = line.split(".")[0]
            flowables.append(safe_paragraph(f"<b>{num}.</b> {content}", styles["DocBullet"]))
        # Blockquotes
        elif line.startswith("> "):
            content = clean_xml_text(line[2:])
            flowables.append(safe_paragraph(f"<i>{content}</i>", styles["DocQuote"]))
        else:
            flowables.append(safe_paragraph(clean_xml_text(line), styles["DocBody"]))

        i += 1

    return flowables


def generate_itinerary_pdf(state: dict, traveler_name: str = "Traveler") -> bytes:
    """
    Generates a beautifully styled, high-resolution PDF document from the TravelState.
    Returns bytes suitable for Streamlit st.download_button.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=42,
        bottomMargin=42
    )

    base_styles = getSampleStyleSheet()

    # Custom Theme Styles (Ocean Blue, Slate, Emerald & Gold)
    styles = {
        "Title": ParagraphStyle(
            "DocTitle",
            parent=base_styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0284C7"),
            alignment=0,
            spaceAfter=4,
        ),
        "Subtitle": ParagraphStyle(
            "DocSubtitle",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#475569"),
            spaceAfter=10,
        ),
        "DocH1": ParagraphStyle(
            "DocH1",
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#0F172A"),
            spaceBefore=12,
            spaceAfter=4,
            keepWithNext=True,
        ),
        "DocH2": ParagraphStyle(
            "DocH2",
            fontName="Helvetica-Bold",
            fontSize=11.5,
            leading=15,
            textColor=colors.HexColor("#0284C7"),
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        ),
        "DocH3": ParagraphStyle(
            "DocH3",
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=colors.HexColor("#0F766E"),
            spaceBefore=8,
            spaceAfter=3,
            keepWithNext=True,
        ),
        "DocH4": ParagraphStyle(
            "DocH4",
            fontName="Helvetica-Bold",
            fontSize=9.5,
            leading=12,
            textColor=colors.HexColor("#334155"),
            spaceBefore=6,
            spaceAfter=2,
            keepWithNext=True,
        ),
        "DocBody": ParagraphStyle(
            "DocBody",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#1E293B"),
            spaceAfter=4,
        ),
        "DocBullet": ParagraphStyle(
            "DocBullet",
            parent=base_styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12.5,
            textColor=colors.HexColor("#334155"),
            leftIndent=14,
            spaceAfter=2.5,
        ),
        "DocQuote": ParagraphStyle(
            "DocQuote",
            parent=base_styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#0369A1"),
            leftIndent=16,
            spaceBefore=4,
            spaceAfter=4,
        ),
        "TableHeader": ParagraphStyle(
            "TableHeader",
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11,
            textColor=colors.white,
        ),
        "TableCell": ParagraphStyle(
            "TableCell",
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#1E293B"),
        ),
        "MetaKey": ParagraphStyle(
            "MetaKey",
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#64748B"),
        ),
        "MetaVal": ParagraphStyle(
            "MetaVal",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=13,
            textColor=colors.HexColor("#0F172A"),
        ),
    }

    elements = []

    # 1. Document Header Banner
    elements.append(safe_paragraph("🧭 AI TRAVEL PLANNER", styles["Title"]))
    dest = clean_xml_text(str(state.get("destination", "Destination")))
    days = state.get("duration_days", 7)
    travel_date = clean_xml_text(str(state.get("travel_date", "Flexible")))
    total_calls = state.get("llm_calls", 0)
    now_str = datetime.now().strftime("%B %d, %Y")
    safe_traveler = clean_xml_text(str(traveler_name))

    elements.append(safe_paragraph(
        f"Customized Itinerary prepared for <b>{safe_traveler}</b> • Generated on {now_str}",
        styles["Subtitle"]
    ))

    # 2. Key Trip Metrics Banner (Table)
    kpi_data = [
        [
            safe_paragraph("DESTINATION", styles["MetaKey"]),
            safe_paragraph("TRIP DURATION", styles["MetaKey"]),
            safe_paragraph("TRAVEL WINDOW", styles["MetaKey"]),
            safe_paragraph("AGENT CALLS", styles["MetaKey"]),
        ],
        [
            safe_paragraph(f"📍 {dest}", styles["MetaVal"]),
            safe_paragraph(f"⏱️ {days} Days", styles["MetaVal"]),
            safe_paragraph(f"📅 {travel_date}", styles["MetaVal"]),
            safe_paragraph(f"🧠 {total_calls} Calls", styles["MetaVal"]),
        ]
    ]
    kpi_table = Table(kpi_data, colWidths=[140, 120, 160, 110])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0F9FF")),
        ("BORDER", (0, 0), (-1, -1), 1, colors.HexColor("#BAE6FD")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 14))

    # 3. Master Itinerary Section
    itinerary_text = state.get("itinerary", "")
    if itinerary_text:
        elements.append(safe_paragraph("🗺️ Master Day-by-Day Itinerary", styles["DocH1"]))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0284C7"), spaceAfter=8))
        elements.extend(markdown_to_flowables(itinerary_text, styles))
        elements.append(Spacer(1, 12))

    # 4. Lodging & Accommodations Section
    hotel_text = state.get("hotel_results", "")
    if hotel_text:
        elements.append(safe_paragraph("🏨 Accommodations & Lodging Research", styles["DocH1"]))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#059669"), spaceAfter=8))
        elements.extend(markdown_to_flowables(hotel_text, styles))
        elements.append(Spacer(1, 12))

    # 5. Flights & Transit Section
    flight_text = state.get("flight_results", "")
    if flight_text:
        elements.append(safe_paragraph("✈️ Flight Discovery & Pricing Benchmarks", styles["DocH1"]))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#2563EB"), spaceAfter=8))
        elements.extend(markdown_to_flowables(flight_text, styles))
        elements.append(Spacer(1, 12))

    # 6. Sights & Local Dining Section
    places_text = state.get("places_results", "")
    if places_text:
        elements.append(safe_paragraph("🏛️ Attractions, Culture & Dining Guide", styles["DocH1"]))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#D97706"), spaceAfter=8))
        elements.extend(markdown_to_flowables(places_text, styles))
        elements.append(Spacer(1, 12))

    # 7. Weather Profile Section
    weather_text = state.get("weather_results", "")
    if weather_text:
        elements.append(safe_paragraph("🌤️ Climate & Meteorological Intel", styles["DocH1"]))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0D9488"), spaceAfter=8))
        elements.extend(markdown_to_flowables(weather_text, styles))

    # Build PDF with dynamic header/footer canvas
    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
